name: Machine Learning Workflow CI

on:
  push:
    branches:
      - main

jobs:
  mlflow-ci-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas scikit-learn virtualenv

    - name: Configure MLflow tracking to SQLite
      run: echo "MLFLOW_TRACKING_URI=sqlite:///${{ github.workspace }}/mlflow.db" >> $GITHUB_ENV

    - name: Setup MLflow Project Git
      run: |
        cd ./MLProject
        git init
        git config user.email "missnapalet@gmail.com"
        git config user.name "Asmaul Husna Bot"
        git add .
        git commit -m "Initial commit for MLflow environment tracking"
        cd ..

    - name: Run MLflow Project
      run: |
        mlflow run ./MLProject --entry-point main -P n_estimators=100 --env-manager local

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker Image
      run: |
        python -c "
        import os, mlflow, subprocess
        
        mlflow.set_tracking_uri(os.environ['MLFLOW_TRACKING_URI'])
        
        # Ambil eksperimen aktif yang didefinisikan pada script modelling.py Anda
        experiment = mlflow.get_experiment_by_name('Getcontact_Sentiment_CI')
        if not experiment:
            raise ValueError('Eksperimen Getcontact_Sentiment_CI tidak ditemukan di Database!')
            
        # Ambil riwayat run terbaru secara akurat dari SQLite database 
        runs = mlflow.search_runs(experiment_ids=[experiment.experiment_id], order_by=['attributes.start_time DESC'], max_results=1)
        if runs.empty:
            raise FileNotFoundError('Tidak ada rekaman run MLflow yang ditemukan di dalam SQLite database!')
            
        latest_run_id = runs.iloc[0]['run_id']
        model_uri = f'runs:/{latest_run_id}/model'
        print(f'Membangun Docker dari URI Model Resmi: {model_uri}')
        
        image_name = '${{ secrets.DOCKER_HUB_USERNAME }}/getcontact-model:latest'
        cmd = f'mlflow models build-docker -m {model_uri} -n {image_name} --enable-mlflow-deployment'
        subprocess.run(cmd, shell=True, check=True)
        "

    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/getcontact-model:latest

    - name: Upload to GitHub
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Automated Bot: Upload re-trained model artifacts [skip ci]"
        file_pattern: 'mlruns/* mlflow.db'
